import type { Metadata } from "next";
import "./globals.css";
import "./icons.css";
import Provider from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={"font-poppins tracking-wide bg-gray-50 bg-cross-pattern"}
      >
        {children}
      </body>
    </html>
  );
}
